<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/06/04 16:56:37

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=cheques',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
