<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/09/14 20:49:09

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ospep',
  'username' => 'root',
  'password' => 123123123,
  'name' => 'doctrine',
)),);
